### ISSUE TITLE
BLE Proxy / ESP-IDF

### ISSUE THREAD

**Issue by sNiXx** [Tysonpower/HCPBridgeMqtt_tynet#14]
Hi @Tysonpower, I was just reading a bit on the BLE proxy functionality of ESPHome and was wondering if you had tested any of this? My use case is that I would like to use a Shelly BLU Button 1 to open my garage door and the device would be in a perfect location to use as a BLE proxy.

If I read the documentation at [Bluetooth Proxy](https://esphome.io/components/bluetooth_proxy) correctly, I think a few changes would be necessary, because:
- _The ESP32 Platform component should be configured to use the esp-idf framework, as the arduino framework uses significantly more memory and performs poorly with the Bluetooth proxy enabled._ 
- _The ESP-IDF framework [...] is recommended for variants of the ESP32 like ESP32S2, ESP32S3, ESP32C3 and single-core ESP32 chips._
- _The Web Server Component component should be disabled as the device is likely to run out of memory and will malfunction when both components are enabled simultaneously._

Of course, the device should be partitioned due to differences between the Arduino and ESP-IDF framework.

``` yaml
packages:
  tynet.hcpbridge_e4: github://Tysonpower/HCPBridgeMqtt_tynet/esphome.yaml@main

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: esp-idf

web_server: !remove

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

**Comment by Tysonpower** [comment]
Nice idea, did you try to just compile and test it like that? If so, did it work?

**Comment by sNiXx** [comment]
No, I was a bit hesitant, as I am still quite new to ESP32/ESPHome and was worried I could brick my device while partitioning 😆

Can you think of any negative side effects? As far as I can tell from the documentation and some additional research, the ESP-IDF framework should be mainly beneficial, as it removes the Arduino layer (which itself seems to be using ESP-IDF underneath), so that would definitely be something I would be interested in as well.

**Comment by Tysonpower** [comment]
You can' really brick an ESP32S3 like on my PCBs, so don't worry.

I think ESP-IDF in ESPHome has some issues with some libraries, but it should work, Arduino does use esp-idf in the background that's correct :)

**Comment by sNiXx** [comment]
I tried to compile it today, but received an error regarding a missing Arduino dependency, which kind of makes sense to me. However, I am not quite sure what the solution would be.

Also, I was thinking of giving the BLE proxy a try without ESP-IDF, but how would I perceive "poor performance", as mentioned in the docs?

<details>
<summary>hcpbridge.yaml</summary>

```
packages:
  tynet.hcpbridge_e4: github://Tysonpower/HCPBridgeMqtt_tynet/esphome.yaml@main

esp32:
  board: adafruit_feather_esp32s3
  framework:
    type: esp-idf

web_server: !remove

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

</details>

<details>
<summary>logs</summary>

```
In file included from src/esphome/components/hcpbridge/button/../hcpbridge.h:9,
                 from src/esphome/components/hcpbridge/button/hcpbridge_button.h:5,
                 from src/esphome/components/hcpbridge/button/hcpbridge_button.cpp:1:
src/esphome/components/hcpbridge/button/../hoermann.h:7:10: fatal error: Arduino.h: No such file or directory

*****************************************************************
* Looking for Arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Arduino.h"
* Web  > https://registry.platformio.org/search?q=header:Arduino.h
*
*****************************************************************

    7 | #include <Arduino.h>
      |          ^~~~~~~~~~~
compilation terminated.
*** [.pioenvs/hcpbridge/src/esphome/components/hcpbridge/button/hcpbridge_button.cpp.o] Error 1
========================= [FAILED] Took 440.23 seconds =========================
```


</details>

**Comment by Tysonpower** [comment]
looks like the hörmann code used the arduino lib, i will try some things in the next days and let you know

**Comment by sNiXx** [comment]
That would be much appreciated, thank you 😃

I just attempted to compile for the Arduino framework (I'm a bit curious, but also impatient 😜 ) and ran into an error regarding program size.

<details>
<summary>hcpbridge.yaml</summary>

```
packages:
  tynet.hcpbridge_e4: github://Tysonpower/HCPBridgeMqtt_tynet/esphome.yaml@main

web_server: !remove

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

</details>

<details>
<summary>logs</summary>

```Error: The program size (1510665 bytes) is greater than maximum allowed (1441792 bytes)
*** [checkprogsize] Explicit exit, status 1
RAM:   [==        ]  21.0% (used 68836 bytes from 327680 bytes)
Flash: [==========]  104.8% (used 1510665 bytes from 1441792 bytes)
========================= [FAILED] Took 292.16 seconds =========================
```

</details>

**Comment by sNiXx** [comment]
I was able to reduce the size just enough by removing many additional parts from the yaml file. However, before I install this firmware on my device: Were you able to figure something out regarding Arduino.h?

<details>
<summary>hcpbridge.yaml</summary>

```
packages:
  tynet.hcpbridge_e4: github://Tysonpower/HCPBridgeMqtt_tynet/esphome.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

# adjustments to save space
sensor: !remove
captive_portal: !remove
i2c: !remove
improv_serial: !remove
web_server: !remove
logger:
  level: INFO
```

</details>
